-- MySQL Script generated by MySQL Workbench
-- 04/26/17 05:59:13
-- Model: BtcRelax    Version: 1.03
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Ident
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Customers` ;

CREATE TABLE IF NOT EXISTS `Customers` (
  `idCustomer` VARCHAR(34) NOT NULL,
  `CreateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isBaned` BIT(1) NOT NULL DEFAULT b'0',
  `ChangeDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Preferences` NVARCHAR(1024) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idCustomer_UNIQUE` ON `Customers` (`idCustomer` ASC);


-- -----------------------------------------------------
-- Table `PubKeys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PubKeys` ;

CREATE TABLE IF NOT EXISTS `PubKeys` (
  `idPubKey` INT NOT NULL AUTO_INCREMENT,
  `idOwner` VARCHAR(34) NOT NULL ,
  `CreateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `xPubKey` VARCHAR(112) NOT NULL,
  `EndDate` TIMESTAMP NULL,
  PRIMARY KEY (`idPubKey`, `idOwner`))
ENGINE = InnoDB;

CREATE INDEX `fk_PubKeys_Customers1_idx` ON `PubKeys` (`idOwner` ASC);

CREATE UNIQUE INDEX `xPubKey_UNIQUE` ON `PubKeys` (`xPubKey` ASC);


-- ALTER TABLE `PubKeys` 
-- ADD CONSTRAINT `fk_PubKeys_Customers1`
--   FOREIGN KEY (`idOwner`)
--   REFERENCES `Customers` (`idCustomer`)
--   ON DELETE CASCADE
--   ON UPDATE NO ACTION;

-- -----------------------------------------------------
-- ,-- 
--   CONSTRAINT `fk_PubKeys_Customers1`
--     FOREIGN KEY (`idOwner`)
--     REFERENCES `Customers` (`idCustomer`)
--     ON DELETE CASCADE
--     ON UPDATE NO ACTION
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InvoiceAddress` ;

CREATE TABLE IF NOT EXISTS `InvoiceAddress` (
  `idInvoiceAddress` INT NOT NULL AUTO_INCREMENT,
  `idPubKey` INT NOT NULL,
  `InvoiceAddres` VARCHAR(34) NOT NULL,
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Balance` DECIMAL(12,8) NULL DEFAULT 0,
  PRIMARY KEY (`idInvoiceAddress`, `idPubKey`),
  CONSTRAINT `fk_InvoiceAddress_PubKeys1`
    FOREIGN KEY (`idPubKey`)
    REFERENCES `PubKeys` (`idPubKey`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_InvoiceAddress_PubKeys1_idx` ON `InvoiceAddress` (`idPubKey` ASC);

CREATE UNIQUE INDEX `InvoiceAddres_UNIQUE` ON `InvoiceAddress` (`InvoiceAddres` ASC);


-- -----------------------------------------------------
-- Table `Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Orders` ;

CREATE TABLE IF NOT EXISTS `Orders` (
  `idOrder` INT(11) NOT NULL AUTO_INCREMENT,
  `CreateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NULL,
  `OrderState` ENUM('Created', 'Confirmed', 'Paid', 'WaitForPayment', 'Canceled', 'Finished') NULL DEFAULT 'Created',
  `BTCPrice` DECIMAL(12,8) NOT NULL,
  `PricingDate` TIMESTAMP NULL,
  `InvoiceAddress` VARCHAR(34) NOT NULL,
  `idCreator` VARCHAR(34) NOT NULL,
  `DeliveryMethod` ENUM('HotHiddenPoint', 'OrderedHotPoint', 'PostOffice') NULL DEFAULT 'HotHiddenPoint',
  `InvoiceBalance` DECIMAL(12,8) NULL,
  `BalanceDate` TIMESTAMP NULL,
  PRIMARY KEY (`idOrder`, `idCreator`),
  CONSTRAINT `fk_Orders_CustomersCreator`
    FOREIGN KEY (`idCreator`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inv_addr`
    FOREIGN KEY (`InvoiceAddress`)
    REFERENCES `InvoiceAddress` (`InvoiceAddres`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

CREATE INDEX `fk_Orders_CustomersCreator_idx` ON `Orders` (`idCreator` ASC);

CREATE UNIQUE INDEX `InvoiceAddress_UNIQUE` ON `Orders` (`InvoiceAddress` ASC);


-- -----------------------------------------------------
-- Table `Bookmarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bookmarks` ;

CREATE TABLE IF NOT EXISTS `Bookmarks` (
  `idBookmark` INT(11) NOT NULL AUTO_INCREMENT,
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idOrder` INT(11) NULL,
  `Quantity` DECIMAL(12,2) NOT NULL,
  `EndDate` TIMESTAMP NULL DEFAULT NULL,
  `Latitude` DECIMAL(12,8) NOT NULL,
  `Longitude` DECIMAL(12,8) NOT NULL,
  `Link` VARCHAR(256) NULL DEFAULT NULL,
  `Description` VARCHAR(1024) NULL DEFAULT NULL,
  `RegionTitle` VARCHAR(45) NULL DEFAULT NULL,
  `CustomPrice` DECIMAL(12,2) NULL DEFAULT NULL,
  `PriceCurrency` ENUM('UAH', 'BTC', 'EUR', 'USD') NOT NULL DEFAULT 'UAH',
  `AdvertiseTitle` VARCHAR(45) NOT NULL,
  `UnlockDate` TIMESTAMP NULL,
  `State` ENUM('Preparing', 'Checking', 'Rejected', 'Ready', 'Published', 'Saled', 'Lost', 'PreOrdered') NULL DEFAULT 'Preparing',
  `IdDroper` VARCHAR(34) NOT NULL,
  `TargetAddress` VARCHAR(34) NOT NULL,
  PRIMARY KEY (`idBookmark`, `IdDroper`),
  CONSTRAINT `fk_droper`
    FOREIGN KEY (`IdDroper`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderId`
    FOREIGN KEY (`idOrder`)
    REFERENCES `Orders` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `Latitude` ON `Bookmarks` (`Latitude` ASC, `Longitude` ASC);

CREATE INDEX `fk_droper_idx` ON `Bookmarks` (`IdDroper` ASC);

CREATE INDEX `fk_OrderId_idx` ON `Bookmarks` (`idOrder` ASC);


-- -----------------------------------------------------
-- Table `CustomersHierarhy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomersHierarhy` ;

CREATE TABLE IF NOT EXISTS `CustomersHierarhy` (
  `CustomersParent` VARCHAR(34) NOT NULL,
  `CustomersChild` VARCHAR(34) NOT NULL,
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CustomersParent`, `CustomersChild`),
  CONSTRAINT `fk_CustomersHierarhy_Parent`
    FOREIGN KEY (`CustomersParent`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomersHierarhy_Child`
    FOREIGN KEY (`CustomersChild`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Customers_has_Customers_Customers1_idx` ON `CustomersHierarhy` (`CustomersParent` ASC);

CREATE INDEX `fk_CustomersHierarhy_Child_idx` ON `CustomersHierarhy` (`CustomersChild` ASC);


-- -----------------------------------------------------
-- Table `Idetities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Idetities` ;

CREATE TABLE IF NOT EXISTS `Idetities` (
  `CreateDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idIdentity` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IdentTypeCode` ENUM('bitid', 'email') NULL DEFAULT NULL,
  `IdentityKey` VARCHAR(50) NULL DEFAULT NULL,
  `EndDate` TIMESTAMP NULL DEFAULT NULL,
  `idCustomer` VARCHAR(34) NOT NULL,
  PRIMARY KEY (`idIdentity`, `idCustomer`),
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `uq_ident` ON `Idetities` (`IdentTypeCode` ASC, `IdentityKey` ASC);

CREATE INDEX `idx_Idetities_IdentTypeCode` ON `Idetities` (`IdentTypeCode` ASC);

CREATE INDEX `fk_customer_idx` ON `Idetities` (`idCustomer` ASC);


-- -----------------------------------------------------
-- Table `tbl_auth_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_auth_log` ;

CREATE TABLE IF NOT EXISTS `tbl_auth_log` (
  `s_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `s_address` VARCHAR(34) NOT NULL,
  `s_ip` VARCHAR(46) NOT NULL,
  `s_description` VARCHAR(4069) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbl_nonces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tbl_nonces` ;

CREATE TABLE IF NOT EXISTS `tbl_nonces` (
  `s_ip` VARCHAR(46) NOT NULL,
  `dt_datetime` DATETIME NOT NULL,
  `s_nonce` VARCHAR(32) NOT NULL,
  `s_address` VARCHAR(34) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `s_nonce` ON `tbl_nonces` (`s_nonce` ASC);

CREATE INDEX `dt_datetime` ON `tbl_nonces` (`dt_datetime` ASC);


-- -----------------------------------------------------
-- Table `Rights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Rights` ;

CREATE TABLE IF NOT EXISTS `Rights` (
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NULL,
  `RightCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RightCode`));


-- -----------------------------------------------------
-- Table `AccessRights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccessRights` ;

CREATE TABLE IF NOT EXISTS `AccessRights` (
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idCustomer` VARCHAR(34) NOT NULL,
  `RightCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`, `RightCode`),
  CONSTRAINT `fk_AccessRights_Customers1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AccessRights_Rights1`
    FOREIGN KEY (`RightCode`)
    REFERENCES `Rights` (`RightCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_AccessRights_Customers1_idx` ON `AccessRights` (`idCustomer` ASC);

CREATE INDEX `fk_AccessRights_Rights1_idx` ON `AccessRights` (`RightCode` ASC);


-- -----------------------------------------------------
-- Table `RootMessages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RootMessages` ;

CREATE TABLE IF NOT EXISTS `RootMessages` (
  `idRootMessage` INT(11) NOT NULL AUTO_INCREMENT,
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ReceiveDate` TIMESTAMP NULL,
  `RootMessage` VARCHAR(1024) NULL,
  `idCustomer` VARCHAR(34) NOT NULL,
  PRIMARY KEY (`idRootMessage`, `idCustomer`),
  CONSTRAINT `fk_RootMessages_Customers1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `errorMessages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `errorMessages` ;

CREATE TABLE IF NOT EXISTS `errorMessages` (
  `ErrorId` INT(11) NOT NULL AUTO_INCREMENT,
  `Message` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`ErrorId`));


-- -----------------------------------------------------
-- Table `PropertyType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PropertyType` ;

CREATE TABLE IF NOT EXISTS `PropertyType` (
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `EndDate` TIMESTAMP NULL,
  `PropertyTypeCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PropertyTypeCode`));


-- -----------------------------------------------------
-- Table `CustomerProperty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CustomerProperty` ;

CREATE TABLE IF NOT EXISTS `CustomerProperty` (
  `CreateDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `idCustomer` VARCHAR(34) NOT NULL,
  `PropertyTypeCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`, `PropertyTypeCode`),
  CONSTRAINT `fk_AccessRights_Customers10`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `Customers` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerProperty_PropertyType1`
    FOREIGN KEY (`PropertyTypeCode`)
    REFERENCES `PropertyType` (`PropertyTypeCode`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);

CREATE INDEX `fk_AccessRights_Customers1_idx` ON `CustomerProperty` (`idCustomer` ASC);

CREATE INDEX `fk_CustomerProperty_PropertyType1_idx` ON `CustomerProperty` (`PropertyTypeCode` ASC);


-- -----------------------------------------------------
-- Placeholder table for view `vwActualPoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vwActualPoint` (`IdBookmark` INT, `CreateDate` INT, `IdOrder` INT, `Quantity` INT, `EndDate` INT, `Latitude` INT, `Longitude` INT, `Link` INT, `Description` INT, `RegionTitle` INT, `CustomPrice` INT, `PriceCurrency` INT, `AdvertiseTitle` INT, `UnlockDate` INT, `State` INT, `IdDroper` INT);

-- -----------------------------------------------------
-- Placeholder table for view `vwCustomerBitid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vwCustomerBitid` (`idCustomer` INT, `BitId` INT);

-- -----------------------------------------------------
-- Placeholder table for view `vwOrders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vwOrders` (`idOrder` INT, `CreateDate` INT, `EndDate` INT, `OrderState` INT, `BTCPrice` INT, `PricingDate` INT, `InvoiceAddress` INT, `idCreator` INT, `DeliveryMethod` INT, `InvoiceBalance` INT, `BalanceDate` INT, `OrderHash` INT);

-- -----------------------------------------------------
-- Placeholder table for view `vwBookmarks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vwBookmarks` (`idBookmark` INT, `CreateDate` INT, `idOrder` INT, `Quantity` INT, `EndDate` INT, `Latitude` INT, `Longitude` INT, `Link` INT, `Description` INT, `RegionTitle` INT, `CustomPrice` INT, `PriceCurrency` INT, `AdvertiseTitle` INT, `UnlockDate` INT, `State` INT, `IdDroper` INT, `TargetAddress` INT, `BookmarkHash` INT);

-- -----------------------------------------------------
-- procedure CreateCustomerByBitId
-- -----------------------------------------------------
DROP procedure IF EXISTS `CreateCustomerByBitId`;

DELIMITER $$
CREATE PROCEDURE `CreateCustomerByBitId`(IN pBitId VARCHAR(50), 
 IN pRecoveryMail VARCHAR(50),
 OUT out_id int)
BEGIN

		DECLARE newCust Varchar(34);
		DECLARE error BOOLEAN DEFAULT FALSE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET error = TRUE;
		SET autocommit= 0;
		SET out_id = 0;
		SET newCust = pBitId;

		START TRANSACTION;
		INSERT INTO Customers (idCustomer)	
			VALUES	(newCust);
	
		INSERT INTO Idetities( IdentTypeCode, IdentityKey, idCustomer)
			VALUES( 'bitid', pBitId  , newCust );

		
		IF (not (pRecoveryMail = '' OR pRecoveryMail is null) ) THEN
			INSERT INTO Idetities( IdentTypeCode, IdentityKey, idCustomer)
				VALUES( 'email', LOWER(pRecoveryMail)  , newCust );

		END IF;

		IF error THEN
				ROLLBACK;
				SET out_id = -1;
		ELSE
				COMMIT;   
		END IF;
		SET autocommit= 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure RegisterOrder4HotPoint
-- -----------------------------------------------------
DROP procedure IF EXISTS `RegisterOrder4HotPoint`;

DELIMITER $$
CREATE PROCEDURE RegisterOrder4HotPoint (IN pIdCustomer varchar(34), IN pBTCPrice decimal(12,8),
IN pBookMarkId int(11), IN pInvoiceAddress varchar(34)  , OUT out_id int, OUT pOrderId int )
BEGIN
		DECLARE vUpdateCnt int default 0;
		DECLARE error BOOLEAN DEFAULT FALSE;
		DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET error = TRUE;
        
		SET autocommit= 0;        
		SET out_id = 0;
        
		START TRANSACTION;
        
        INSERT INTO Orders
			(`OrderState`,
			`BTCPrice`,
			`InvoiceAddress`,
            `idCreator`
            )
			VALUES
			('WaitForPayment',
            pBTCPrice,
            pInvoiceAddress,
            pIdCustomer);
		
		SELECT LAST_INSERT_ID() INTO pOrderId;
        
		UPDATE Bookmarks 
		SET 
			IdOrder = pOrderId,
			State = 'PreOrdered'
		WHERE
			IdBookmark = pBookMarkId
        AND IdOrder IS NULL
        AND UnlockDate IS NULL;
                
		SELECT ROW_COUNT() INTO vUpdateCnt;
               
		IF error THEN
				ROLLBACK;
				SET out_id = -1;
		ELSE
			begin
				IF (vUpdateCnt = 1) then					
					COMMIT;
				else
					rollback;
                    SET pOrderId = 0;
                    SET out_id = 101;
				END IF;
            
            end;
		END IF;
		SET autocommit= 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure CancelOrder
-- -----------------------------------------------------
DROP procedure IF EXISTS `CancelOrder`;

DELIMITER $$
CREATE  PROCEDURE CancelOrder(IN pOrderId int, OUT pResult int)
BEGIN

UPDATE `Orders`
SET
`OrderState` = 'Canceled', 
`EndDate` = NOW()
WHERE `idOrder` = pOrderId;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure FinishOrder
-- -----------------------------------------------------
DROP procedure IF EXISTS `FinishOrder`;

DELIMITER $$
CREATE  PROCEDURE FinishOrder(IN pOrderId int, OUT pResult int)
BEGIN

UPDATE `Orders`
SET
`OrderState` = 'Finished', 
`EndDate` = NOW()
WHERE `idOrder` = pOrderId;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- function UpdateHotBalance
-- -----------------------------------------------------
DROP function IF EXISTS `UpdateHotBalance`;

DELIMITER $$
CREATE  FUNCTION UpdateHotBalance( pOrderId int, pBalance decimal(12,8)) RETURNS boolean
BEGIN		
    DECLARE vStateChanged bool default 0;
    DECLARE vPrice decimal(12,8);
    DECLARE vInvoiceBalance decimal(12,8);
    
    SELECT BTCPrice, InvoiceBalance
	INTO vPrice , vInvoiceBalance
	FROM Orders 
	WHERE idOrder  = pOrderId;
	
    IF (pBalance = vInvoiceBalance) THEN
				SET vStateChanged = 0;
			ELSE 
			    SET vStateChanged = 1;
                
			
				IF (pBalance >= vPrice) THEN
					update Orders
						SET InvoiceBalance = pBalance , BalanceDate = NOW(), OrderState = 'Paid' 
						WHERE idOrder = pOrderId;
				ELSE
					update Orders
						SET InvoiceBalance = pBalance , BalanceDate = NOW()
						WHERE idOrder = pOrderId;               
                END if;
            end if;
	RETURN vStateChanged;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function GetHashByOrderId
-- -----------------------------------------------------
DROP function IF EXISTS `GetHashByOrderId`;

DELIMITER $$
CREATE FUNCTION GetHashByOrderId(pIdOrder integer) RETURNS varchar(32) CHARSET utf8
BEGIN
	DECLARE vidOrder int;
	DECLARE vOrderState varchar(20);
	DECLARE vBTCPrice  decimal(12,8);
	DECLARE vInvoiceAddress varchar(34);
	DECLARE vInvoiceBalance decimal(12,8);
	DECLARE vResult varchar(32);

SELECT 
    idOrder,
    OrderState,
    BTCPrice,
    InvoiceAddress,
    InvoiceBalance
INTO vidOrder , vOrderState , vBTCPrice , vInvoiceAddress , vInvoiceBalance FROM
    Orders
WHERE
    idOrder = pIdOrder;
	
    SELECT MD5(CONCAT_WS(vidOrder, vOrderState,vBTCPrice,  vInvoiceAddress,vInvoiceBalance))
    INTO vResult;
    
RETURN vResult;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function GetHashByBookmarkId
-- -----------------------------------------------------
DROP function IF EXISTS `GetHashByBookmarkId`;

DELIMITER $$
CREATE FUNCTION GetHashByBookmarkId (pIdBookmark int) RETURNS varchar(32)
BEGIN
	DECLARE vIdBookmark int(11);
	DECLARE vIdOrder int(11);
	DECLARE vQuantity decimal(12,2);
	DECLARE vLatitude decimal(12,8);
	DECLARE vLongitude decimal(12,8);
	DECLARE vLink varchar(256);
	DECLARE vDescription varchar(1024);
	DECLARE vRegionTitle varchar(45);
	DECLARE vCustomPrice decimal(12,2);
	DECLARE vPriceCurrency varchar(3);
	DECLARE vAdvertiseTitle varchar(45);
	DECLARE vState varchar(25);
	DECLARE vIdDroper varchar(34);
	DECLARE vTargetAddress varchar(34);
	DECLARE vResult varchar(32);
  
SELECT 
    idBookmark,
    idOrder,
    Quantity,
    Latitude,
    Longitude,
    Link,
    Description,
    RegionTitle,
    CustomPrice,
    PriceCurrency,
    AdvertiseTitle,
    State,
    IdDroper,
    TargetAddress
INTO vIdBookmark , vIdOrder , vQuantity , vLatitude , vLongitude , vLink , vDescription , vRegionTitle , vCustomPrice , vPriceCurrency , vAdvertiseTitle , vState , vIdDroper , vTargetAddress FROM
    Bookmarks
WHERE
    idBookmark = pIdBookmark;

SELECT 
    MD5(CONCAT_WS(vIdBookmark,
                    vIdOrder,
                    vQuantity,
                    vLatitude,
                    vLongitude,
                    vLink,
                    vDescription,
                    vRegionTitle,
                    vCustomPrice,
                    vPriceCurrency,
                    vAdvertiseTitle,
                    vState,
                    vIdDroper,
                    vTargetAddress))
INTO vResult;

RETURN vResult;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function GetPubKeyByCustomer
-- -----------------------------------------------------
DROP function IF EXISTS `GetPubKeyByCustomer`;

DELIMITER $$
CREATE FUNCTION GetPubKeyByCustomer (pIdCustomer varchar(34)) RETURNS varchar(112)
BEGIN
	DECLARE vResult varchar(112);
  
SELECT xPubKey
INTO 	vResult 
FROM    PubKeys
WHERE idOwner = pIdCustomer 
AND (now() <= coalesce( EndDate,now())) AND (now()>CreateDate);

RETURN vResult;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function AddInvoiceAddressToXPub
-- -----------------------------------------------------
DROP function IF EXISTS `AddInvoiceAddressToXPub`;

DELIMITER $$
CREATE FUNCTION AddInvoiceAddressToXPub (pXPubKey varchar(112), pInvoiceAddres varchar(34)) RETURNS int(11)
BEGIN
	DECLARE vIdPubKey int;
    DECLARE vAddressId int;
    
    SELECT idPubKey
    INTO vIdPubKey
    FROM PubKeys
    WHERE xPubKey = pXPubKey;
    
    INSERT INTO InvoiceAddress (idPubKey, InvoiceAddres, CreateDate, Balance) 
	VALUES (vIdPubKey, pInvoiceAddres , DEFAULT, DEFAULT);
    
	RETURN LAST_INSERT_ID();
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function GetInvoiceAddressCountByXPub
-- -----------------------------------------------------
DROP function IF EXISTS `GetInvoiceAddressCountByXPub`;

DELIMITER $$
CREATE FUNCTION GetInvoiceAddressCountByXPub (pXPubKey varchar(112)) RETURNS int
BEGIN
	DECLARE vResult int;
    
    SELECT count(*)
    INTO vResult
    FROM InvoiceAddress
    WHERE xPubKey = pXPubKey;
    
    RETURN vResult ;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `vwActualPoint`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `vwActualPoint` ;
DROP TABLE IF EXISTS `vwActualPoint`;
CREATE  OR REPLACE VIEW `vwActualPoint` AS select `Bookmarks`.`IdBookmark` AS `IdBookmark`,`Bookmarks`.`CreateDate` AS `CreateDate`,`Bookmarks`.`IdOrder` AS `IdOrder`,`Bookmarks`.`Quantity` AS `Quantity`,`Bookmarks`.`EndDate` AS `EndDate`,`Bookmarks`.`Latitude` AS `Latitude`,`Bookmarks`.`Longitude` AS `Longitude`,`Bookmarks`.`Link` AS `Link`,`Bookmarks`.`Description` AS `Description`,`Bookmarks`.`RegionTitle` AS `RegionTitle`,`Bookmarks`.`CustomPrice` AS `CustomPrice`,`Bookmarks`.`PriceCurrency` AS `PriceCurrency`,`Bookmarks`.`AdvertiseTitle` AS `AdvertiseTitle`,`Bookmarks`.`UnlockDate` AS `UnlockDate`,`Bookmarks`.`State` AS `State`,`Bookmarks`.`IdDroper` AS `IdDroper` from `Bookmarks` where (isnull(`Bookmarks`.`IdOrder`) and (now() <= coalesce(`Bookmarks`.`EndDate`,now())));

-- -----------------------------------------------------
-- View `vwCustomerBitid`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `vwCustomerBitid` ;
DROP TABLE IF EXISTS `vwCustomerBitid`;
CREATE  OR REPLACE VIEW `vwCustomerBitid` AS select `Customers`.`idCustomer` AS `idCustomer`,`Idetities`.`IdentityKey` AS `BitId` from (`Customers` join `Idetities` on(((`Idetities`.`IdentTypeCode` = 'bitid') and (`Idetities`.`idCustomer` = `Customers`.`idCustomer`))));

-- -----------------------------------------------------
-- View `vwOrders`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `vwOrders` ;
DROP TABLE IF EXISTS `vwOrders`;
CREATE  OR REPLACE VIEW vwOrders AS
    SELECT 
        idOrder,
        CreateDate,
        EndDate,
        OrderState,
        BTCPrice,
        PricingDate,
        InvoiceAddress,
        idCreator,
        DeliveryMethod,
        InvoiceBalance,
        BalanceDate,
        GETHASHBYORDERID(idOrder) AS OrderHash
    FROM
        Orders;

-- -----------------------------------------------------
-- View `vwBookmarks`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `vwBookmarks` ;
DROP TABLE IF EXISTS `vwBookmarks`;
CREATE  OR REPLACE VIEW `vwBookmarks` AS
SELECT `Bookmarks`.`idBookmark`,
    `Bookmarks`.`CreateDate`,
    `Bookmarks`.`idOrder`,
    `Bookmarks`.`Quantity`,
    `Bookmarks`.`EndDate`,
    `Bookmarks`.`Latitude`,
    `Bookmarks`.`Longitude`,
    `Bookmarks`.`Link`,
    `Bookmarks`.`Description`,
    `Bookmarks`.`RegionTitle`,
    `Bookmarks`.`CustomPrice`,
    `Bookmarks`.`PriceCurrency`,
    `Bookmarks`.`AdvertiseTitle`,
    `Bookmarks`.`UnlockDate`,
    `Bookmarks`.`State`,
    `Bookmarks`.`IdDroper`,
    `Bookmarks`.`TargetAddress`,
     GetHashByBookmarkId(idBookmark) as BookmarkHash
FROM `Bookmarks`;

-- -----------------------------------------------------
-- Data for table `Customers`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `Customers` (`idCustomer`, `CreateDate`, `isBaned`, `ChangeDate`, `Preferences`) VALUES ('1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN', DEFAULT, 0, NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `PubKeys`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `PubKeys` (`idPubKey`, `idOwner`, `CreateDate`, `xPubKey`, `EndDate`) VALUES (DEFAULT, '1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN', '2016-03-30 03:41:28', 'xpub661MyMwAqRbcGgwGvP3MbDaUKTEpppjwJZoqZLGS59ystwUKVNhbueXEwRH19nTFm9jFC2fZtgcmkj8a77de1HudQ8Uw4sdq9pA4deTMVdh', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Bookmarks`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `Bookmarks` (`idBookmark`, `CreateDate`, `idOrder`, `Quantity`, `EndDate`, `Latitude`, `Longitude`, `Link`, `Description`, `RegionTitle`, `CustomPrice`, `PriceCurrency`, `AdvertiseTitle`, `UnlockDate`, `State`, `IdDroper`, `TargetAddress`) VALUES (DEFAULT, '2016-03-30 03:41:28', NULL, 1, NULL, 50.4594524, 30.4213277, 'https://fastfen.club/cloud/index.php/s/9Fj4xrS1shlRs4k', '', 'Киев, м.Берестейская', 50, DEFAULT, 'Папироса ганджубаса', NULL, 'Published', '1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN', '19obTLBfmhyiirETcThD1ydMkWGFLuDaqe');
INSERT INTO `Bookmarks` (`idBookmark`, `CreateDate`, `idOrder`, `Quantity`, `EndDate`, `Latitude`, `Longitude`, `Link`, `Description`, `RegionTitle`, `CustomPrice`, `PriceCurrency`, `AdvertiseTitle`, `UnlockDate`, `State`, `IdDroper`, `TargetAddress`) VALUES (DEFAULT, '2016-03-30 03:41:28', NULL, 2, NULL, 50.4590367, 30.6299849, 'https://fastfen.club/cloud/index.php/s/hthgwc2vPGLA9QT', NULL, 'Киев, м.Черниговская', 100, DEFAULT, 'Пол пакета ганджубаса', NULL, 'Published', '1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN', '19obTLBfmhyiirETcThD1ydMkWGFLuDaqe');
INSERT INTO `Bookmarks` (`idBookmark`, `CreateDate`, `idOrder`, `Quantity`, `EndDate`, `Latitude`, `Longitude`, `Link`, `Description`, `RegionTitle`, `CustomPrice`, `PriceCurrency`, `AdvertiseTitle`, `UnlockDate`, `State`, `IdDroper`, `TargetAddress`) VALUES (DEFAULT, '2016-03-30 03:41:28', NULL, 1, NULL, 50.4620083, 30.4174780, 'https://fastfen.club/cloud/index.php/s/1Xhds3PuEpmK1We', NULL, 'Киев, м.Берестейская', 100, DEFAULT, '0,25 амфетамина', NULL, 'Published', '1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN', '19obTLBfmhyiirETcThD1ydMkWGFLuDaqe');
INSERT INTO `Bookmarks` (`idBookmark`, `CreateDate`, `idOrder`, `Quantity`, `EndDate`, `Latitude`, `Longitude`, `Link`, `Description`, `RegionTitle`, `CustomPrice`, `PriceCurrency`, `AdvertiseTitle`, `UnlockDate`, `State`, `IdDroper`, `TargetAddress`) VALUES (DEFAULT, '2016-03-30 03:41:28', NULL, 2, NULL, 50.4569520, 30.4346062, 'https://fastfen.club/cloud/index.php/s/rD7rIToXz1gXGHZ', NULL, 'Киев, м.Шулявка', 100, DEFAULT, 'Пол пакета ганджубаса', NULL, 'Published', '1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN', '19obTLBfmhyiirETcThD1ydMkWGFLuDaqe');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Idetities`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `Idetities` (`CreateDate`, `idIdentity`, `IdentTypeCode`, `IdentityKey`, `EndDate`, `idCustomer`) VALUES (DEFAULT, DEFAULT, 'bitid', '1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN', NULL, '1Fk8Q3LWcEaqcfpQp6Zv4jNJwdUMutttmN');

COMMIT;


-- -----------------------------------------------------
-- Data for table `errorMessages`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `errorMessages` (`ErrorId`, `Message`) VALUES (101, 'Error when assign hot point to order');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
