<!DOCTYPE html>
<html>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" rel="stylesheet" type=
          "text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
          rel="stylesheet" type="text/css">
    <link href="css/styles.css" rel="stylesheet" type="text/css">
    <link href="css/show_message.css" rel="stylesheet" type="text/css" >
    <link href="css/jquery-ui.min.css" rel="stylesheet">
    <link href="css/notify.css" rel="stylesheet" type="text/css">

    <link rel="stylesheet" type="text/css" href="js/app/app.css">
    <link rel="stylesheet" type="text/css" href="css/w3.css">		
    <script type="text/javascript" src="js/jquery-1.11.3.min.js" ></script>		
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/notify.js" ></script>   		
    <script type="text/javascript" src="js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="js/dhtmlx.js"></script>
    <script type="text/javascript" src="js/app/app.js"></script>         		
    <script type="text/javascript" src="js/app/copoban.js"></script>


    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0px;
            overflow: hidden;
        }
    </style>


    <body class="bgimg w3-container" onload="doOnLoad();" onunload="doOnUnload();" >
        <nav>
            <div class="navbar-header">                       
                <button id="idMainButton" class="logo" >                            
                    <img src="/img/ff2_128.gif" />
                </button>
                <?php
                if (isset($header)) {
                    ?>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                <?php }; ?>				
            </div>
            <?php
            if (isset($header)) {
                echo $header->GetHeaderHtml($page);
            }
            ?>			
        </nav>
        <div id="copobanId"  class="w3-display-middle" style="display: none;">
<?php require $template; ?>
        </div>
        <footer>
           <script>
			$( document ).ready( function() {
                               updateSessionState('<?php  echo($core->getSessionState()); ?>'); 
                            });
	
            </script>            
        </footer>
    </body>
</html>
