<h3>BitId:</h3>
<p><?php echo ($_SESSION['user_id']); ?></p>
<p>
<div id='tawk_58262da6780fc531d6e6ee35'></div>
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date(); Tawk_API.embedded='tawk_58262da6780fc531d6e6ee35';
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=false;
s1.src='https://embed.tawk.to/58262da6780fc531d6e6ee35/1b1movtd3';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);})();
</script>
<!--End of Tawk.to Script-->
</p>                                    
 
