<script>
//    var myToolbar = new dhtmlXToolbarObject();
//    myToolbar.addText("info", 15, "Core:<?php echo $version ?>");
//    var myLayout = new dhtmlXLayoutObject(document.body,"2U"); 
//    myLayout.cells("a").setWidth(250);
//    myLayout.cells("a").setText("Files"); 
//    myLayout.cells("b").hideHeader();
//    var myToolbar = myLayout.attachToolbar(); 
    dhtmlxEvent(window,"load",function(){
        var dhxWins = new dhtmlXWindows();
        var layoutWin  = dhxWins.createWindow("rootWindow", 20, 20, 600, 400);
        layoutWin.button("close").disable();
        layoutWin.setText("Core:<?php echo $version ?>");
        var myLayout = layoutWin.attachLayout("2U");       
        myLayout.cells("a").setText("Sessions");
        var sessionsGrid = myLayout.cells("a").attachGrid();
        sessionsGrid.setHeader("SessionId,Expires");
        sessionsGrid.setInitWidths("350,350");   
        sessionsGrid.setColumnIds("sid,expires");
        sessionsGrid.setColAlign("left,left");     //sets the alignment of columns
        sessionsGrid.setColTypes("ro,ro");               //sets the types of columns
        sessionsGrid.setColSorting("str,str");
        sessionsGrid.init();
        sessionsGrid.load("data/SessionsApi.php");   
        myLayout.cells("b").setText("Sessions variables");
        var sessionForm = myLayout.cells("b").attachForm();
        sessionForm.loadStruct("data/form.xml");
        var menu = layoutWin.attachMenu();
        menu.setIconsPath("img/icons/");
        menu.loadStruct("data/menu.xml");
        var myToolbar = layoutWin.attachToolbar(); 
        myToolbar.setIconsPath("img/icons/");
        myToolbar.loadStruct("data/toolbarStruct.xml");
    });
</script>