<?php

namespace BtcRelax;

        use \BtcRelax\SecureSession; 
    
        global $core;
        
        if ($core->getSessionState() === SecureSession::STATUS_UNAUTH)
        { ?>
            
                <div id="copobanContentId" class="w3-animate-zoom starter-template" >
                    <h1 style="font-family: museo-slab, Georgia, 'Times New Roman', Times, serif; font-weight: 500; 
                        text-shadow: 4px 3px 0px #1d9d74, 9px 8px 0px rgba(0, 0, 0, 0.15);">
                        CopoBan !</h1>
                    <form id="frmLogin" action="#"  method="post" >
                        <input name="nonce" value="<?php echo $_SESSION['nonce']; ?>" type="hidden" />
                        <a href="<?php echo $authParams['bitid_uri']; ?>">
                        <img  class="loginQr" alt="Click on QRcode to activate compatible desktop wallet" border="0" 
                              src="<?php echo $authParams['qr_uri']; ?>" />
                    </a>                        
                    <script type="text/javascript">
                        $(document).ready(function () {
                            //Handler for .ready() called.					

                            var myInterval = setInterval(function () {
                                var r = new XMLHttpRequest();
                                r.open("POST", "<?php echo $authParams['ajax_uri']; ?>", true);
                                r.onreadystatechange = function () {
                                    if (r.readyState != 4 || r.status != 200)
                                        return;
                                    if (r.responseText === 'true') {
                                            $(document.getElementById('copobanId')).hide("slow");
                                            clearInterval(myInterval);                                                                       
                                            $('#frmLogin').submit();             
                                         };
                                };
                                r.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');                              
                                r.send("nonce=<?php echo $_SESSION['nonce']; ?>")
                            }, 30000);
                        });


                    </script>
                    </form>
                </div>
        <?php }




